//---------------------------------------------------------------------------*
//                                                                           *
//                          File 'grammaireBDD.h'                            *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     february 7th, 2010, at 20h59'19"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef GRAMMAR_grammaireBDD_HAS_BEEN_DEFINED
#define GRAMMAR_grammaireBDD_HAS_BEEN_DEFINED

//---------------------------------------------------------------------------*

#include "syntaxeBDD.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*

class C_Grammar_grammaireBDD : public syntaxeBDD {
  public : virtual void nt_analyserFormule_ (C_Lexique_lexiqueBDD &,
                                             GGS_typeTableFormules &,
                                             GGS_typeDomainMap &,
                                             GGS_typeListeCalculs &,
                                             GGS_luint) ;

  public : virtual void nt_argsFormelsFormule_ (C_Lexique_lexiqueBDD &,
                                                GGS_typeTableVariablesBool &,
                                                GGS_uint &,
                                                GGS_typeDomainMap &,
                                                GGS_typeFormalArgumentsList &) ;

  public : virtual void nt_axiomeBDD_ (C_Lexique_lexiqueBDD &,
                                       GGS_typeTableFormules &,
                                       GGS_typeListeCalculs &,
                                       GGS_typeDomainMap &) ;

  public : static void _performSourceFileParsing_ (C_Compiler & inCompiler,
                                                   const C_String & inDependancyExtension,
                                                   const C_String & inDependancyPath,
                                                   GGS_string * inSentStringPtr,
                                                   const GGS_lstring inFileName,
                                                   GGS_typeTableFormules &,
                                                   GGS_typeListeCalculs &,
                                                   GGS_typeDomainMap &
                                                   COMMA_LOCATION_ARGS) ;

  public : static void _performSourceStringParsing_ (C_Compiler & inCompiler,
                                                     GGS_string * inSentStringPtr,
                                                     const GGS_string inSourceString,
                                                     GGS_typeTableFormules &,
                                                     GGS_typeListeCalculs &,
                                                     GGS_typeDomainMap &
                                                     COMMA_LOCATION_ARGS) ;

  public : virtual void nt_comparaisonVariable_ (C_Lexique_lexiqueBDD &,
                                                 GGS_typeTableVariablesBool,
                                                 GGS_luint,
                                                 GGS_luint,
                                                 GGS_luint,
                                                 GGS_luint,
                                                 GGS_luint,
                                                 GGS_typeFormule &) ;

  public : virtual void nt_declarations_ (C_Lexique_lexiqueBDD &,
                                          GGS_typeTableVariablesBool &,
                                          GGS_uint &,
                                          GGS_typeDomainMap &,
                                          GGS_typeFormalArgumentsList &) ;

  public : virtual void nt_dimension_ (C_Lexique_lexiqueBDD &,
                                       GGS_typeDomainMap &,
                                       GGS_typeDomain &) ;

  public : virtual void nt_domainDefinition_ (C_Lexique_lexiqueBDD &,
                                              GGS_typeDomainMap &,
                                              GGS_typeDomain &) ;

  public : virtual void nt_egalite_formule_ (C_Lexique_lexiqueBDD &,
                                             GGS_typeTableVariablesBool,
                                             GGS_uint,
                                             GGS_typeDomainMap &,
                                             GGS_typeTableFormules &,
                                             GGS_typeFormule &) ;

  public : virtual void nt_facteur_formule_ (C_Lexique_lexiqueBDD &,
                                             GGS_typeTableVariablesBool,
                                             GGS_uint,
                                             GGS_typeDomainMap &,
                                             GGS_typeTableFormules &,
                                             GGS_typeFormule &) ;

  public : virtual void nt_formule_ (C_Lexique_lexiqueBDD &,
                                     GGS_typeTableVariablesBool,
                                     GGS_uint,
                                     GGS_typeDomainMap &,
                                     GGS_typeTableFormules &,
                                     GGS_typeFormule &) ;

  public : virtual void nt_parse_argument_ (C_Lexique_lexiqueBDD &,
                                            GGS_typeTableVariablesBool &,
                                            GGS_typeVariableDescriptor &,
                                            GGS_location &) ;

  public : virtual void nt_parse_scalar_argument_ (C_Lexique_lexiqueBDD &,
                                                   GGS_typeTableVariablesBool &,
                                                   GGS_luint &,
                                                   GGS_luint &,
                                                   GGS_luint &,
                                                   GGS_luint &,
                                                   GGS_location &) ;

  public : virtual void nt_terme_formule_ (C_Lexique_lexiqueBDD &,
                                           GGS_typeTableVariablesBool,
                                           GGS_uint,
                                           GGS_typeDomainMap &,
                                           GGS_typeTableFormules &,
                                           GGS_typeFormule &) ;

  public : virtual void nt_type_formule_ (C_Lexique_lexiqueBDD &,
                                          GGS_typeTableVariablesBool,
                                          GGS_uint,
                                          GGS_typeDomainMap &,
                                          GGS_typeTableFormules &,
                                          GGS_lstring,
                                          GGS_typeFormalArgumentsList,
                                          GGS_luint,
                                          GGS_typeCalcul &) ;

  public : virtual PMSInt16 select_syntaxeBDD_0 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_1 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_2 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_3 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_4 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_5 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_6 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_7 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_8 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_9 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_10 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_11 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_12 (C_Lexique_lexiqueBDD &) ;

  public : virtual PMSInt16 select_syntaxeBDD_13 (C_Lexique_lexiqueBDD &) ;
} ;

//---------------------------------------------------------------------------*

#endif
