//---------------------------------------------------------------------------*
//                                                                           *
//                          File 'grammaireBDD.h'                            *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 9th, 2008, at 14h15'45"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef GRAMMAR_grammaireBDD_HAS_BEEN_DEFINED
#define GRAMMAR_grammaireBDD_HAS_BEEN_DEFINED

//---------------------------------------------------------------------------*

#include "syntaxeBDD.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*

class grammaireBDD : public syntaxeBDD {
  public : virtual void nt_analyserFormule_ (lexiqueBDD &,
                                GGS_typeTableFormules &,
                                GGS_typeDomainMap &,
                                GGS_typeListeCalculs &,
                                GGS_luint) ;
  public : virtual void nt_argsFormelsFormule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool &,
                                GGS_uint &,
                                GGS_typeDomainMap &,
                                GGS_typeFormalArgumentsList &) ;
  public : virtual void nt_axiomeBDD_ (lexiqueBDD &,
                                GGS_typeTableFormules &,
                                GGS_typeListeCalculs &,
                                GGS_typeDomainMap &) ;
  public : static void _performSourceFileParsing_ (C_Compiler & _inCompiler,
                                const GGS_lstring & inFileName,
                                GGS_typeTableFormules &,
                                GGS_typeListeCalculs &,
                                GGS_typeDomainMap &
                                COMMA_LOCATION_ARGS) ;
  public : virtual void nt_comparaisonVariable_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool,
                                GGS_luint,
                                GGS_luint,
                                GGS_luint,
                                GGS_luint,
                                GGS_luint,
                                GGS_typeFormule &) ;
  public : virtual void nt_declarations_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool &,
                                GGS_uint &,
                                GGS_typeDomainMap &,
                                GGS_typeFormalArgumentsList &) ;
  public : virtual void nt_dimension_ (lexiqueBDD &,
                                GGS_typeDomainMap &,
                                GGS_typeDomain &) ;
  public : virtual void nt_domainDefinition_ (lexiqueBDD &,
                                GGS_typeDomainMap &,
                                GGS_typeDomain &) ;
  public : virtual void nt_egalite_formule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool,
                                GGS_uint,
                                GGS_typeDomainMap &,
                                GGS_typeTableFormules &,
                                GGS_typeFormule &) ;
  public : virtual void nt_facteur_formule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool,
                                GGS_uint,
                                GGS_typeDomainMap &,
                                GGS_typeTableFormules &,
                                GGS_typeFormule &) ;
  public : virtual void nt_formule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool,
                                GGS_uint,
                                GGS_typeDomainMap &,
                                GGS_typeTableFormules &,
                                GGS_typeFormule &) ;
  public : virtual void nt_parse_argument_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool &,
                                GGS_typeVariableDescriptor &,
                                GGS_location &) ;
  public : virtual void nt_parse_scalar_argument_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool &,
                                GGS_luint &,
                                GGS_luint &,
                                GGS_luint &,
                                GGS_luint &,
                                GGS_location &) ;
  public : virtual void nt_terme_formule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool,
                                GGS_uint,
                                GGS_typeDomainMap &,
                                GGS_typeTableFormules &,
                                GGS_typeFormule &) ;
  public : virtual void nt_type_formule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool,
                                GGS_uint,
                                GGS_typeDomainMap &,
                                GGS_typeTableFormules &,
                                GGS_lstring,
                                GGS_typeFormalArgumentsList,
                                GGS_luint,
                                GGS_typeCalcul &) ;
  public : virtual sint16 select_repeat_syntaxeBDD_0 (lexiqueBDD &) ;
  public : virtual sint16 select_syntaxeBDD_1 (lexiqueBDD &) ;
  public : virtual sint16 select_syntaxeBDD_2 (lexiqueBDD &) ;
  public : virtual sint16 select_syntaxeBDD_3 (lexiqueBDD &) ;
  public : virtual sint16 select_repeat_syntaxeBDD_4 (lexiqueBDD &) ;
  public : virtual sint16 select_syntaxeBDD_5 (lexiqueBDD &) ;
  public : virtual sint16 select_repeat_syntaxeBDD_6 (lexiqueBDD &) ;
  public : virtual sint16 select_syntaxeBDD_7 (lexiqueBDD &) ;
  public : virtual sint16 select_syntaxeBDD_8 (lexiqueBDD &) ;
  public : virtual sint16 select_repeat_syntaxeBDD_9 (lexiqueBDD &) ;
  public : virtual sint16 select_repeat_syntaxeBDD_10 (lexiqueBDD &) ;
  public : virtual sint16 select_repeat_syntaxeBDD_11 (lexiqueBDD &) ;
  public : virtual sint16 select_repeat_syntaxeBDD_12 (lexiqueBDD &) ;
  public : virtual sint16 select_repeat_syntaxeBDD_13 (lexiqueBDD &) ;
} ;

//---------------------------------------------------------------------------*

#endif
