//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_typeFormuleImplique.h'                    *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                       march 4th, 2006, at 18h3'5"                         *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     class 'cPtr_typeFormuleImplique'                      *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeFormuleImplique_DEFINED
#define typeFormuleImplique_DEFINED

class cPtr_typeFormuleImplique : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const long /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

  public : cPtr_typeFormuleImplique (const GGS_typeFormule & ,
                                const GGS_typeFormule &  COMMA_LOCATION_ARGS) ;
  public : GGS_typeFormule  aOperande1 ;
  public : GGS_typeFormule  aOperande2 ;
} ;

//---------------------------------------------------------------------------*

#endif

