//---------------------------------------------------------------------------*
//                                                                           *
//                     File 'include_typeFormuleFor.h'                       *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                    september 21th, 2009, at 21h4'40"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                   abstract class 'cPtr_typeFormuleFor'                    *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeFormuleFor : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const PMSInt32 /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_typeFormuleFor (const GGS_luint & ,
                                const GGS_typeActualArgumentsList & ,
                                const GGS_extern_bdd& ,
                                const GGS_lbool & 
                                COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virtual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~cPtr_typeFormuleFor (void) {}
  #endif

//--- Attributes
  public : GGS_luint  mNumeroFormule ;
  public : GGS_typeActualArgumentsList  mListeArgsBool ;
  public : GGS_extern_bdd mFormuleTraduite ;
  public : GGS_lbool  mEstFormuleCourante ;
//--- Class message
  public : virtual const char * _message (void) const ;
  public : static const char * _static_message (void) ;

//--- Method for 'description' reader
  public : virtual void
  appendForDescription (C_Compiler & inLexique,
                        C_String & ioString,
                        const PMSInt32 inIndentation
                        COMMA_LOCATION_ARGS) const ;

//--- Comparison
  public : virtual bool
  isEqualToObject (const cPtr__AC_galgas_class * inOperand) const ;

//--- Galgas RTTI
  public : virtual AC_galgasClassRunTimeInformation * galgasRTTI (void) const ;

//--- Make clone
  public : virtual cPtr__AC_galgas_class * makeClone (void) const ;
} ;

//---------------------------------------------------------------------------*

