//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'include_typeFormuleExist.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      april 23th, 2006, at 21h28'51"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                      class 'cPtr_typeFormuleExist'                        *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeFormuleExist_DEFINED
#define typeFormuleExist_DEFINED

class cPtr_typeFormuleExist : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const sint32 /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

  public : cPtr_typeFormuleExist (const GGS_typeFormalArgumentsList & ,
                                const GGS_typeFormule & ,
                                const GGS_bdd&  COMMA_LOCATION_ARGS) ;
  public : GGS_typeFormalArgumentsList  mListeArgsBooleens ;
  public : GGS_typeFormule  mOperand ;
  public : GGS_bdd mContraints ;
  public : virtual void appendForDescription (C_String & ioString) const ;
} ;

//---------------------------------------------------------------------------*

#endif

