//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'include_typeFormuleFalse.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                       june 6th, 2006, at 22h41'30"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                      class 'cPtr_typeFormuleFalse'                        *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeFormuleFalse : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const sint32 /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

  public : cPtr_typeFormuleFalse (LOCATION_ARGS) ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

