//---------------------------------------------------------------------------*
//                                                                           *
//                     File 'include_typeUse_AND_ITE.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 20th, 2006, at 12h1'16"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                       class 'cPtr_typeUse_AND_ITE'                        *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeUse_AND_ITE_DEFINED
#define typeUse_AND_ITE_DEFINED

class cPtr_typeUse_AND_ITE : public cPtr_typeCalcul {
  private : typedef cPtr_typeCalcul inherited ;
//--- START OF USER ZONE 2

public : virtual void executerCalcul (TC_UniqueArray <C_BDD> & tabValeurFormules) ;

//--- END OF USER ZONE 2

  public : cPtr_typeUse_AND_ITE (LOCATION_ARGS) ;
  public : virtual void appendForDescription (C_String & ioString) const ;
} ;

//---------------------------------------------------------------------------*

#endif

