//---------------------------------------------------------------------------*
//                                                                           *
//                 File 'include_typeVariableDescriptor.h'                   *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      april 25th, 2006, at 18h47'27"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//               abstract class 'cPtr_typeVariableDescriptor'                *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeVariableDescriptor_DEFINED
#define typeVariableDescriptor_DEFINED

//---------------------------------------------------------------------------*

class cPtr_typeVariableDescriptor : public C_GGS_Object {
//--- START OF USER ZONE 2

  public : virtual void computeBoundsConstraint (C_BDD & ioConstraint) const = 0 ;
  public : virtual sint32 getBDDvariablesCount (void) const = 0 ;
  public : virtual void defineBDDvariableNames (C_Display_BDD & ioBDDvariableNameArray,
                                                const C_String & inVariableName,
                                                uint32 & ioIndex) const = 0 ;

//--- END OF USER ZONE 2

  public : cPtr_typeVariableDescriptor (LOCATION_ARGS) ;
  public : virtual const char * message_variableDescriptorErrorMessage (void) const ;
  public : static const char * static_string_message_variableDescriptorErrorMessage (void) ;
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const = 0 ;
} ;

//---------------------------------------------------------------------------*

#endif

