//---------------------------------------------------------------------------*
//                                                                           *
//                File 'include_typeDimensionnerANDCache.h'                  *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 20th, 2006, at 12h1'16"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                  class 'cPtr_typeDimensionnerANDCache'                    *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeDimensionnerANDCache_DEFINED
#define typeDimensionnerANDCache_DEFINED

class cPtr_typeDimensionnerANDCache : public cPtr_typeCalcul {
  private : typedef cPtr_typeCalcul inherited ;
//--- START OF USER ZONE 2

public : virtual void executerCalcul (TC_UniqueArray <C_BDD> & tabValeurFormules) ;

//--- END OF USER ZONE 2

  public : cPtr_typeDimensionnerANDCache (const GGS_luint &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  aDimensionCache ;
  public : virtual void appendForDescription (C_String & ioString) const ;
} ;

//---------------------------------------------------------------------------*

#endif

