//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'include_typeFormuleFalse.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 12th, 2006, at 21h54'10"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                      class 'cPtr_typeFormuleFalse'                        *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeFormuleFalse_DEFINED
#define typeFormuleFalse_DEFINED

class cPtr_typeFormuleFalse : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const long /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

  public : cPtr_typeFormuleFalse (LOCATION_ARGS) ;
} ;

//---------------------------------------------------------------------------*

class GGG_typeFormuleFalse : public GGG_typeFormule {
  private : typedef GGG_typeFormule inherited ;
  public : GGG_typeFormuleFalse (LOCATION_ARGS) ;
} ;

//---------------------------------------------------------------------------*

#endif

