//---------------------------------------------------------------------------*
//                                                                           *
//             File 'include_typeFormuleComparaisonVariable.h'               *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      january 22th, 2007, at 22h8'8"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//           abstract class 'cPtr_typeFormuleComparaisonVariable'            *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeFormuleComparaisonVariable : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const sint32 /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_typeFormuleComparaisonVariable (const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint &  COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~cPtr_typeFormuleComparaisonVariable (void) {}
  #endif

  public : GGS_luint  mIndiceBDDgauche ;
  public : GGS_luint  mDimension ;
  public : GGS_luint  mLeftLowBound ;
  public : GGS_luint  mLeftHighBound ;
  public : GGS_luint  mComparaison ;
  public : GGS_luint  mIndiceBDDdroite ;
  public : GGS_luint  mRightLowBound ;
  public : GGS_luint  mRightHighBound ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
//--- Comparison
  public : virtual bool isEqualToObject (const C_GGS_Object * inOperand) const ;
} ;

//---------------------------------------------------------------------------*

