//---------------------------------------------------------------------------*
//                                                                           *
//              File 'include_typeFormuleComparaisonValeur.h'                *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                       may 28th, 2006, at 19h38'47"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                class 'cPtr_typeFormuleComparaisonValeur'                  *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeFormuleComparaisonValeur : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const sint32 /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

  public : cPtr_typeFormuleComparaisonValeur (const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  mIndiceBDD ;
  public : GGS_luint  mDimension ;
  public : GGS_luint  mLowBound ;
  public : GGS_luint  mHighBound ;
  public : GGS_luint  mComparaison ;
  public : GGS_luint  mValeur ;
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

