//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_typeDirectVariable.h'                     *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      april 25th, 2006, at 18h47'28"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     class 'cPtr_typeDirectVariable'                       *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeDirectVariable_DEFINED
#define typeDirectVariable_DEFINED

class cPtr_typeDirectVariable : public cPtr_typeVariableDescriptor {
  private : typedef cPtr_typeVariableDescriptor inherited ;
//--- START OF USER ZONE 2

  public : virtual void computeBoundsConstraint (C_BDD & ioConstraint) const ;
  public : virtual sint32 getBDDvariablesCount (void) const ;
  public : virtual sint32 getBDDslotCount (void) const ;
  public : virtual void defineBDDvariableNames (C_Display_BDD & ioBDDvariableNameArray,
                                                const C_String & inVariableName,
                                                uint32 & ioIndex) const ;

//--- END OF USER ZONE 2

  public : cPtr_typeDirectVariable (const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  mIndex ;
  public : GGS_luint  mBitSize ;
  public : GGS_luint  mLowBound ;
  public : GGS_luint  mHighBound ;
  public : virtual const char * message_variableDescriptorErrorMessage (void) const ;
  public : static const char * static_string_message_variableDescriptorErrorMessage (void) ;
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

#endif

