//---------------------------------------------------------------------------*
//                                                                           *
//                       File 'include_typeCalcul.h'                         *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 16th, 2006, at 18h57'49"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     abstract class 'cPtr_typeCalcul'                      *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeCalcul_DEFINED
#define typeCalcul_DEFINED

//---------------------------------------------------------------------------*

class cPtr_typeCalcul : public C_GGS_Object {
//--- START OF USER ZONE 2

public : virtual void executerCalcul (TC_UniqueArray <C_BDD> & tabValeurFormules) = 0 ;

//--- END OF USER ZONE 2

  public : cPtr_typeCalcul (LOCATION_ARGS) ;
} ;

//---------------------------------------------------------------------------*

/* class GGG_typeCalcul : public C_GGS_Object {
  public : GGG_typeCalcul (LOCATION_ARGS) ;
} ; */

//---------------------------------------------------------------------------*

#endif

