//---------------------------------------------------------------------------*
//                                                                           *
//                 File 'include_typeComparaisonFormules.h'                  *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 20th, 2006, at 12h1'16"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                   class 'cPtr_typeComparaisonFormules'                    *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeComparaisonFormules_DEFINED
#define typeComparaisonFormules_DEFINED

class cPtr_typeComparaisonFormules : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const long /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

  public : cPtr_typeComparaisonFormules (const GGS_luint & ,
                                const GGS_typeFormule & ,
                                const GGS_typeFormule &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  aComparaison ;
  public : GGS_typeFormule  aOperande1 ;
  public : GGS_typeFormule  aOperande2 ;
  public : virtual void appendForDescription (C_String & ioString) const ;
} ;

//---------------------------------------------------------------------------*

#endif

