//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'include_typeAfficherBilan.h'                     *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 12th, 2006, at 21h54'10"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                      class 'cPtr_typeAfficherBilan'                       *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeAfficherBilan_DEFINED
#define typeAfficherBilan_DEFINED

class cPtr_typeAfficherBilan : public cPtr_typeCalcul {
  private : typedef cPtr_typeCalcul inherited ;
//--- START OF USER ZONE 2

public : virtual void executerCalcul (TC_UniqueArray <C_BDD> & tabValeurFormules) ;

//--- END OF USER ZONE 2

  public : cPtr_typeAfficherBilan (LOCATION_ARGS) ;
} ;

//---------------------------------------------------------------------------*

class GGG_typeAfficherBilan : public GGG_typeCalcul {
  private : typedef GGG_typeCalcul inherited ;
  public : GGG_typeAfficherBilan (LOCATION_ARGS) ;
} ;

//---------------------------------------------------------------------------*

#endif

