//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'include_typeDirectDomain.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      january 22th, 2007, at 22h8'8"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                  abstract class 'cPtr_typeDirectDomain'                   *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeDirectDomain : public cPtr_typeDomain {
  private : typedef cPtr_typeDomain inherited ;
//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_typeDirectDomain (const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint &  COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~cPtr_typeDirectDomain (void) {}
  #endif

  public : GGS_luint  mLowBound ;
  public : GGS_luint  mHighBound ;
  public : GGS_luint  mBitsCount ;
  public : virtual const char * message_messageDomainType (void) const ;
  public : static const char * static_string_message_messageDomainType (void) ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
//--- Comparison
  public : virtual bool isEqualToObject (const C_GGS_Object * inOperand) const ;
} ;

//---------------------------------------------------------------------------*

