//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'include_typeCalculSimple.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                       may 28th, 2006, at 19h38'47"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                      class 'cPtr_typeCalculSimple'                        *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeCalculSimple : public cPtr_typeCalcul {
  private : typedef cPtr_typeCalcul inherited ;
//--- START OF USER ZONE 2

public : virtual void executerCalcul (TC_UniqueArray <C_BDD> & tabValeurFormules) ;

//--- END OF USER ZONE 2

  public : cPtr_typeCalculSimple (const GGS_luint & ,
                                const GGS_typeFormule & ,
                                const GGS_lstring & ,
                                const GGS_typeTableVariablesBool & ,
                                const GGS_luint &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  mNumeroFormule ;
  public : GGS_typeFormule  mFormule ;
  public : GGS_lstring  mNomFormule ;
  public : GGS_typeTableVariablesBool  mTableVariablesBool ;
  public : GGS_luint  mAfficher ;
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

