//---------------------------------------------------------------------------*
//                                                                           *
//             File 'include_typeFormuleComparaisonVariable.h'               *
//                Generated by version 1.0.0 (LL(1) grammar)                 *
//                     october 29th, 2005, at 20h14'47"                      *
//                                                                           *
// This program is free software; you can redistribute it and/or modify it   *
// under the terms of the GNU General Public License as published by the     *
// Free Software Foundation.                                                 *
//                                                                           *
// This program is distributed in the hope it will be useful, but WITHOUT    *
// ANY WARRANTY; without even the implied warranty of MERCHANDIBILITY or     *
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for  *
// more details.                                                             *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//               class 'cPtr_typeFormuleComparaisonVariable'                 *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeFormuleComparaisonVariable_DEFINED
#define typeFormuleComparaisonVariable_DEFINED

class cPtr_typeFormuleComparaisonVariable : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const long /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

  public : cPtr_typeFormuleComparaisonVariable (const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ) ;
  public : GGS_luint  aIndiceBDDgauche ;
  public : GGS_luint  aDimension ;
  public : GGS_luint  mLeftLowBound ;
  public : GGS_luint  mLeftHighBound ;
  public : GGS_luint  aComparaison ;
  public : GGS_luint  aIndiceBDDdroite ;
  public : GGS_luint  mRightLowBound ;
  public : GGS_luint  mRightHighBound ;
} ;

//---------------------------------------------------------------------------*

#endif

