//---------------------------------------------------------------------------*
//                                                                           *
//                       File 'include_typeCalcul.h'                         *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 4th, 2007, at 12h20'52"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     abstract class 'cPtr_typeCalcul'                      *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeCalcul : public C_GGS_Object {
//--- START OF USER ZONE 2

public : virtual void executerCalcul (TC_UniqueArray <C_BDD> & tabValeurFormules) = 0 ;

//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_typeCalcul (LOCATION_ARGS) ;

//--- Declaring a protected virtual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~cPtr_typeCalcul (void) {}
  #endif

//--- Attributes
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;

//--- Comparison
  public : virtual bool isEqualToObject (const C_GGS_Object * inOperand) const = 0 ;
} ;

//---------------------------------------------------------------------------*

