//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'include_typeDirectDomain.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     november 2nd, 2006, at 21h2'36"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                      class 'cPtr_typeDirectDomain'                        *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeDirectDomain : public cPtr_typeDomain {
  private : typedef cPtr_typeDomain inherited ;
//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

  public : cPtr_typeDirectDomain (const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  mLowBound ;
  public : GGS_luint  mHighBound ;
  public : GGS_luint  mBitsCount ;
  public : virtual const char * message_messageDomainType (void) const ;
  public : static const char * static_string_message_messageDomainType (void) ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
//--- Comparison
  public : virtual bool isEqualToObject (const C_GGS_Object * inOperand) const ;
} ;

//---------------------------------------------------------------------------*

