//---------------------------------------------------------------------------*
//                                                                           *
//                  File 'include_typeDimensionnerTable.h'                   *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     november 2nd, 2006, at 21h2'36"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                    class 'cPtr_typeDimensionnerTable'                     *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeDimensionnerTable : public cPtr_typeCalcul {
  private : typedef cPtr_typeCalcul inherited ;
//--- START OF USER ZONE 2

public : virtual void executerCalcul (TC_UniqueArray <C_BDD> & tabValeurFormules) ;

//--- END OF USER ZONE 2

  public : cPtr_typeDimensionnerTable (const GGS_luint &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  mDimensionTable ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
//--- Comparison
  public : virtual bool isEqualToObject (const C_GGS_Object * inOperand) const ;
} ;

//---------------------------------------------------------------------------*

