//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'include_typeFormuleExist.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 21th, 2007, at 14h49'42"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                  abstract class 'cPtr_typeFormuleExist'                   *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeFormuleExist : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const sint32 /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_typeFormuleExist (const GGS_typeFormalArgumentsList & ,
                                const GGS_typeFormule & ,
                                const GGS_extern_bdd& 
                                COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virtual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~cPtr_typeFormuleExist (void) {}
  #endif

//--- Attributes
  public : GGS_typeFormalArgumentsList  mListeArgsBooleens ;
  public : GGS_typeFormule  mOperand ;
  public : GGS_extern_bdd mContraints ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Compiler & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;

//--- Comparison
  public : virtual bool
  isEqualToObject (const C_GGS_Object * inOperand) const ;
} ;

//---------------------------------------------------------------------------*

