//---------------------------------------------------------------------------*
//                                                                           *
//                  File 'include_typeDimensionnerTable.h'                   *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      april 25th, 2006, at 18h47'28"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                    class 'cPtr_typeDimensionnerTable'                     *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeDimensionnerTable_DEFINED
#define typeDimensionnerTable_DEFINED

class cPtr_typeDimensionnerTable : public cPtr_typeCalcul {
  private : typedef cPtr_typeCalcul inherited ;
//--- START OF USER ZONE 2

public : virtual void executerCalcul (TC_UniqueArray <C_BDD> & tabValeurFormules) ;

//--- END OF USER ZONE 2

  public : cPtr_typeDimensionnerTable (const GGS_luint &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  mDimensionTable ;
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

#endif

