//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_typeRecordVariable.h'                     *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     november 2nd, 2006, at 21h2'36"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     class 'cPtr_typeRecordVariable'                       *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeRecordVariable : public cPtr_typeVariableDescriptor {
  private : typedef cPtr_typeVariableDescriptor inherited ;
//--- START OF USER ZONE 2

  public : virtual void computeBoundsConstraint (C_BDD & ioConstraint) const ;
  public : virtual sint32 getBDDvariablesCount (void) const ;
  public : virtual sint32 getBDDslotCount (void) const ;
  public : virtual void defineBDDvariableNames (C_Display_BDD & ioBDDvariableNameArray,
                                                const C_String & inVariableName,
                                                uint32 & ioIndex) const ;

//--- END OF USER ZONE 2

  public : cPtr_typeRecordVariable (const GGS_typeTableVariablesBool &  COMMA_LOCATION_ARGS) ;
  public : GGS_typeTableVariablesBool  mMap ;
  public : virtual const char * message_variableDescriptorErrorMessage (void) const ;
  public : static const char * static_string_message_variableDescriptorErrorMessage (void) ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
//--- Comparison
  public : virtual bool isEqualToObject (const C_GGS_Object * inOperand) const ;
} ;

//---------------------------------------------------------------------------*

