//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'include_typeCalculSimple.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      january 22th, 2007, at 22h8'8"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                  abstract class 'cPtr_typeCalculSimple'                   *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeCalculSimple : public cPtr_typeCalcul {
  private : typedef cPtr_typeCalcul inherited ;
//--- START OF USER ZONE 2

public : virtual void executerCalcul (TC_UniqueArray <C_BDD> & tabValeurFormules) ;

//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_typeCalculSimple (const GGS_luint & ,
                                const GGS_typeFormule & ,
                                const GGS_lstring & ,
                                const GGS_typeTableVariablesBool & ,
                                const GGS_luint &  COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~cPtr_typeCalculSimple (void) {}
  #endif

  public : GGS_luint  mNumeroFormule ;
  public : GGS_typeFormule  mFormule ;
  public : GGS_lstring  mNomFormule ;
  public : GGS_typeTableVariablesBool  mTableVariablesBool ;
  public : GGS_luint  mAfficher ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
//--- Comparison
  public : virtual bool isEqualToObject (const C_GGS_Object * inOperand) const ;
} ;

//---------------------------------------------------------------------------*

