//---------------------------------------------------------------------------*
//                                                                           *
//                       File 'include_typeFormule.h'                        *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                       may 28th, 2006, at 19h38'47"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                    abstract class 'cPtr_typeFormule'                      *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeFormule : public C_GGS_Object {
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) = 0 ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const sint32 /* numeroFormuleCourante */) = 0 ;


//--- END OF USER ZONE 2

  public : cPtr_typeFormule (LOCATION_ARGS) ;
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const = 0 ;
} ;

//---------------------------------------------------------------------------*

