//---------------------------------------------------------------------------*
//                                                                           *
//                      File 'include_typeFormuleEt.h'                       *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 16th, 2006, at 13h13'49"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                        class 'cPtr_typeFormuleEt'                         *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeFormuleEt_DEFINED
#define typeFormuleEt_DEFINED

class cPtr_typeFormuleEt : public cPtr_typeFormule {
  private : typedef cPtr_typeFormule inherited ;
//--- START OF USER ZONE 2

public : virtual C_BDD evaluerFormule (const C_BDD & valeurFormuleCourante) ;
public : virtual void executerLesChangementsDeVariable (TC_UniqueArray <C_BDD> & tabValeurFormules,
                                                        const long /* numeroFormuleCourante */) ;

//--- END OF USER ZONE 2

  public : cPtr_typeFormuleEt (const GGS_typeFormule & ,
                                const GGS_typeFormule &  COMMA_LOCATION_ARGS) ;
  public : GGS_typeFormule  aOperande1 ;
  public : GGS_typeFormule  aOperande2 ;
} ;

//---------------------------------------------------------------------------*

/* class GGG_typeFormuleEt : public GGG_typeFormule {
  private : typedef GGG_typeFormule inherited ;
  public : GGG_typeFormuleEt (const GGS_typeFormule & ,
                                const GGS_typeFormule &  COMMA_LOCATION_ARGS) ;
} ; */

//---------------------------------------------------------------------------*

#endif

