//---------------------------------------------------------------------------*
//                                                                           *
//                     File 'include_typeUse_AND_ITE.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                       may 28th, 2006, at 19h38'47"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                       class 'cPtr_typeUse_AND_ITE'                        *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeUse_AND_ITE : public cPtr_typeCalcul {
  private : typedef cPtr_typeCalcul inherited ;
//--- START OF USER ZONE 2

public : virtual void executerCalcul (TC_UniqueArray <C_BDD> & tabValeurFormules) ;

//--- END OF USER ZONE 2

  public : cPtr_typeUse_AND_ITE (LOCATION_ARGS) ;
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

