//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'include_typeRecordDomain.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 21th, 2007, at 14h49'42"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                  abstract class 'cPtr_typeRecordDomain'                   *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeRecordDomain : public cPtr_typeDomain {
  private : typedef cPtr_typeDomain inherited ;
//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_typeRecordDomain (const GGS_typeDomainMap & 
                                COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virtual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~cPtr_typeRecordDomain (void) {}
  #endif

//--- Attributes
  public : GGS_typeDomainMap  mRecordMap ;
  public : virtual const char * message_messageDomainType (void) const ;
  public : static const char * static_string_message_messageDomainType (void) ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Compiler & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;

//--- Comparison
  public : virtual bool
  isEqualToObject (const C_GGS_Object * inOperand) const ;
} ;

//---------------------------------------------------------------------------*

