//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_typeDirectVariable.h'                     *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      april 15th, 2007, at 10h42'53"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                 abstract class 'cPtr_typeDirectVariable'                  *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_typeDirectVariable : public cPtr_typeVariableDescriptor {
  private : typedef cPtr_typeVariableDescriptor inherited ;
//--- START OF USER ZONE 2

  public : virtual void computeBoundsConstraint (C_BDD & ioConstraint) const ;
  public : virtual sint32 getBDDvariablesCount (void) const ;
  public : virtual sint32 getBDDslotCount (void) const ;
  public : virtual void defineBDDvariableNames (C_Display_BDD & ioBDDvariableNameArray,
                                                const C_String & inVariableName,
                                                uint32 & ioIndex) const ;

//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_typeDirectVariable (const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & ,
                                const GGS_luint & 
                                COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virtual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~cPtr_typeDirectVariable (void) {}
  #endif

//--- Attributes
  public : GGS_luint  mIndex ;
  public : GGS_luint  mBitSize ;
  public : GGS_luint  mLowBound ;
  public : GGS_luint  mHighBound ;
  public : virtual const char * message_variableDescriptorErrorMessage (void) const ;
  public : static const char * static_string_message_variableDescriptorErrorMessage (void) ;
//--- Method for 'description' reader
  public : virtual void
  appendForDescription (C_Compiler & _inLexique,
                        C_String & ioString,
                        const sint32 inIndentation
                        COMMA_LOCATION_ARGS) const ;

//--- Comparison
  public : virtual bool
  isEqualToObject (const cPtr__AC_galgas_class * inOperand) const ;
} ;

//---------------------------------------------------------------------------*

