//---------------------------------------------------------------------------*
//                                                                           *
//                           File 'lexiqueBDD.h'                             *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     january 24th, 2010, at 10h7'38"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1


#ifndef lexiqueBDD_0_DEFINED
#define lexiqueBDD_0_DEFINED

//---------------------------------------------------------------------------*

#include "galgas/GGS_lstring.h"
#include "galgas/GGS_luint.h"
#include "galgas/GGS_lsint.h"
#include "galgas/GGS_luint64.h"
#include "galgas/GGS_lsint64.h"
#include "galgas/GGS_lchar.h"
#include "galgas/GGS_ldouble.h"
#include "galgas/GGS_lbool.h"
#include "galgas-utilities/C_Lexique.h"

//---------------------------------------------------------------------------*
//                                                                           *
//                    E X T E R N    R O U T I N E S                         *
//                                                                           *
//---------------------------------------------------------------------------*

void scanner_routine_formerCompEgal (C_Lexique & inLexique,
                PMUInt32 & ioArgument) ;

void scanner_routine_formerCompInf (C_Lexique & inLexique,
                PMUInt32 & ioArgument) ;

void scanner_routine_formerCompInfEgal (C_Lexique & inLexique,
                PMUInt32 & ioArgument) ;

void scanner_routine_formerCompNonEgal (C_Lexique & inLexique,
                PMUInt32 & ioArgument) ;

void scanner_routine_formerCompSup (C_Lexique & inLexique,
                PMUInt32 & ioArgument) ;

void scanner_routine_formerCompSupEgal (C_Lexique & inLexique,
                PMUInt32 & ioArgument) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                    E X T E R N    F U N C T I O N S                       *
//                                                                           *
//---------------------------------------------------------------------------*

//---------------------------------------------------------------------------*
//                                                                           *
//                       T O K E N    C L A S S                              *
//                                                                           *
//---------------------------------------------------------------------------*

class cTokenFor_lexiqueBDD : public cToken {
  public : C_String mLexicalAttribute_att_idf ;
  public : C_String mLexicalAttribute_att_token ;
  public : PMUInt32 mLexicalAttribute_att_valeur ;

  public : cTokenFor_lexiqueBDD (void) ;
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                     S C A N N E R    C L A S S                            *
//                                                                           *
//---------------------------------------------------------------------------*

class lexiqueBDD : public C_Lexique {
//--- Constructors
  public : lexiqueBDD (C_Compiler * inCallerCompiler,
                       const C_String & inDependencyFileExtension,
                       const C_String & inDependencyFilePath,
                       C_galgas_io * inParametersPtr,
                       const C_String & inSourceFileName
                       COMMA_LOCATION_ARGS) ;

  public : lexiqueBDD (C_Compiler * inCallerCompiler,
                       C_galgas_io * inParametersPtr,
                       const C_String & inSourceString,
                       const C_String & inStringForError
                       COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virtual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~lexiqueBDD (void) {}
  #endif


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


//--- Terminal symbols enumeration
  public : enum {lexiqueBDD_1_,
  lexiqueBDD_1_nombre,
  lexiqueBDD_1_id,
  lexiqueBDD_1_string,
  lexiqueBDD_1_comp,
  lexiqueBDD_1__28_,
  lexiqueBDD_1__29_,
  lexiqueBDD_1__7B_,
  lexiqueBDD_1__7D_,
  lexiqueBDD_1__5B_,
  lexiqueBDD_1__5D_,
  lexiqueBDD_1__3A__3D_,
  lexiqueBDD_1__3A_,
  lexiqueBDD_1__2E_,
  lexiqueBDD_1__2E__2E_,
  lexiqueBDD_1__2B__3D_,
  lexiqueBDD_1__2D__3D_,
  lexiqueBDD_1__2D__3E_,
  lexiqueBDD_1__26_,
  lexiqueBDD_1__7C_,
  lexiqueBDD_1__7E_,
  lexiqueBDD_1__2C_,
  lexiqueBDD_1__3F_,
  lexiqueBDD_1__21_,
  lexiqueBDD_1__3B_,
  lexiqueBDD_1__23_,
  lexiqueBDD_1_ite_5F_cache,
  lexiqueBDD_1_and_5F_cache,
  lexiqueBDD_1_use_5F_and,
  lexiqueBDD_1_use_5F_ite,
  lexiqueBDD_1_use_5F_and_5F_ite,
  lexiqueBDD_1_map,
  lexiqueBDD_1_bdd,
  lexiqueBDD_1_domain,
  lexiqueBDD_1_bool,
  lexiqueBDD_1_record,
  lexiqueBDD_1_true,
  lexiqueBDD_1_false,
  lexiqueBDD_1_display,
  lexiqueBDD_1_include,
  lexiqueBDD_1_dump,
  lexiqueBDD_1_verify,
  lexiqueBDD_1_end,
  lexiqueBDD_1_if,
  lexiqueBDD_1_then,
  lexiqueBDD_1_else} ;

//--- Key words table 'delimiteursKerBDD'
  public : static PMSInt16 search_into_delimiteursKerBDD (const C_String & inSearchedString) ;

//--- Key words table 'motsReservesKerBDD'
  public : static PMSInt16 search_into_motsReservesKerBDD (const C_String & inSearchedString) ;
  

//--- Assign from attribute
  public : void assignFromAttribute_att_idf (GGS_lstring & outValue) const ;
  public : void assignFromAttribute_att_token (GGS_lstring & outValue) const ;
  public : void assignFromAttribute_att_valeur (GGS_luint & outValue) const ;


//--- Attribute access
  public : C_String attributeValue_att_idf (void) const ;
  public : C_String attributeValue_att_token (void) const ;
  public : PMUInt32 attributeValue_att_valeur (void) const ;


//--- Parse lexical token
  protected : virtual bool parseLexicalToken (void) ;

//--- Append terminal message
  protected : virtual void appendTerminalMessageToSyntaxErrorMessage (const PMSInt16 numeroTerminal,
                                                              C_String & messageErreur) ;

//--- Get terminal count
  public : virtual PMSInt16 terminalVocabularyCount (void) const { return 45 ; }

//--- Get Token String
  public : virtual C_String getCurrentTokenString (const cToken * inTokenPtr) const ;

//--- Enter Token
  protected : void enterToken (const cTokenFor_lexiqueBDD & inToken) ;
} ;

//---------------------------------------------------------------------------*

#endif
