//---------------------------------------------------------------------------*
//                                                                           *
//                           File 'lexiqueBDD.h'                             *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                       june 16th, 2009, at 20h37'4"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef lexiqueBDD_0_DEFINED
#define lexiqueBDD_0_DEFINED

//---------------------------------------------------------------------------*

#include "galgas/GGS_lstring.h"
#include "galgas/GGS_luint.h"
#include "galgas/GGS_lsint.h"
#include "galgas/GGS_luint64.h"
#include "galgas/GGS_lsint64.h"
#include "galgas/GGS_lchar.h"
#include "galgas/GGS_ldouble.h"
#include "galgas/GGS_lbool.h"
#include "galgas/C_Lexique.h"

//---------------------------------------------------------------------------*
//                                                                           *
//                          Lexical scanner class                            *
//                                                                           *
//---------------------------------------------------------------------------*

class cTokenFor_lexiqueBDD : public cToken {
  public : C_String mLexicalAttribute_att_idf ;
  public : C_String mLexicalAttribute_att_token ;
  public : uint32 mLexicalAttribute_att_valeur ;

  public : cTokenFor_lexiqueBDD (void) ;
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                          Lexical scanner class                            *
//                                                                           *
//---------------------------------------------------------------------------*

class lexiqueBDD : public C_Lexique {
//--- Constructors
  public : lexiqueBDD (C_Compiler * inCallerCompiler,
                       const C_String & inDependencyFileExtension,
                       const C_String & inDependencyFilePath,
                       C_galgas_io * inParametersPtr,
                       const C_String & inSourceFileName
                       COMMA_LOCATION_ARGS) ;

  public : lexiqueBDD (C_Compiler * inCallerCompiler,
                       C_galgas_io * inParametersPtr,
                       const C_String & inSourceString,
                       const C_String & inStringForError
                       COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virtual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~lexiqueBDD (void) {}
  #endif

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//--- Terminal symbols enumeration
  public : enum {lexiqueBDD_1_,
  lexiqueBDD_1_nombre,
  lexiqueBDD_1_id,
  lexiqueBDD_1_string,
  lexiqueBDD_1_comp,
  lexiqueBDD_1__28_,
  lexiqueBDD_1__29_,
  lexiqueBDD_1__7B_,
  lexiqueBDD_1__7D_,
  lexiqueBDD_1__5B_,
  lexiqueBDD_1__5D_,
  lexiqueBDD_1__3A__3D_,
  lexiqueBDD_1__3A_,
  lexiqueBDD_1__2E_,
  lexiqueBDD_1__2E__2E_,
  lexiqueBDD_1__2B__3D_,
  lexiqueBDD_1__2D__3D_,
  lexiqueBDD_1__2D__3E_,
  lexiqueBDD_1__26_,
  lexiqueBDD_1__7C_,
  lexiqueBDD_1__7E_,
  lexiqueBDD_1__2C_,
  lexiqueBDD_1__3F_,
  lexiqueBDD_1__21_,
  lexiqueBDD_1__3B_,
  lexiqueBDD_1__23_,
  lexiqueBDD_1_ite_5F_cache,
  lexiqueBDD_1_and_5F_cache,
  lexiqueBDD_1_use_5F_and,
  lexiqueBDD_1_use_5F_ite,
  lexiqueBDD_1_use_5F_and_5F_ite,
  lexiqueBDD_1_map,
  lexiqueBDD_1_bdd,
  lexiqueBDD_1_domain,
  lexiqueBDD_1_bool,
  lexiqueBDD_1_record,
  lexiqueBDD_1_true,
  lexiqueBDD_1_false,
  lexiqueBDD_1_display,
  lexiqueBDD_1_include,
  lexiqueBDD_1_dump,
  lexiqueBDD_1_verify,
  lexiqueBDD_1_end,
  lexiqueBDD_1_if,
  lexiqueBDD_1_then,
  lexiqueBDD_1_else} ;

//--- Key words table 'delimiteursKerBDD'
  public : static sint16 search_into_delimiteursKerBDD (const C_String & inSearchedString) ;

//--- Key words table 'motsReservesKerBDD'
  public : static sint16 search_into_motsReservesKerBDD (const C_String & inSearchedString) ;

  protected : virtual bool parseLexicalToken (void) ;
  protected : virtual sint16 parseLexicalTokenForLexicalColoring (void) ;
  protected : virtual void appendTerminalMessageToSyntaxErrorMessage (const sint16 numeroTerminal,
                                                              C_String & messageErreur) ;

//--- Get attribute values
  public : void assignFromAttribute_att_idf (GGS_lstring & outValue) const ;
  public : C_String attributeValue_att_idf (void) const ;
  public : void assignFromAttribute_att_token (GGS_lstring & outValue) const ;
  public : C_String attributeValue_att_token (void) const ;
  public : void assignFromAttribute_att_valeur (GGS_luint & outValue) const ;
  public : uint32 attributeValue_att_valeur (void) const ;
//--- Get terminal count
  public : virtual sint16 terminalVocabularyCount (void) const { return 45 ; }
//--- Get Token String
  public : virtual C_String getCurrentTokenString (const cToken * inTokenPtr) const ;
//--- Enter Token
  protected : void enterToken (const cTokenFor_lexiqueBDD & inToken) ;
//--- Style Definition
  public : static sint32 getStylesCount (void) ;
  public : static const char * getStyleName (const sint32 inIndex) ;
  public : static const char * getStyleIdentifier (const sint32 inIndex) ;
//--- Virtual method called getting terminal style index
  public : virtual uint8 terminalStyleIndex (const sint32 inTerminal) ;
} ;

//---------------------------------------------------------------------------*

#endif
