//---------------------------------------------------------------------------*
//                                                                           *
//                        File 'lexiqueBDD-cocoa.h'                          *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                      july 10th, 2009, at 16h46'49"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1


#import "OC_Lexique.h"

//---------------------------------------------------------------------------*
//                                                                           *
//                    E X T E R N    R O U T I N E S                         *
//                                                                           *
//---------------------------------------------------------------------------*

void scanner_cocoa_routine_formerCompEgal (BOOL * ioScanningOk,
                UInt32 * ioArgument) ;

void scanner_cocoa_routine_formerCompInf (BOOL * ioScanningOk,
                UInt32 * ioArgument) ;

void scanner_cocoa_routine_formerCompInfEgal (BOOL * ioScanningOk,
                UInt32 * ioArgument) ;

void scanner_cocoa_routine_formerCompNonEgal (BOOL * ioScanningOk,
                UInt32 * ioArgument) ;

void scanner_cocoa_routine_formerCompSup (BOOL * ioScanningOk,
                UInt32 * ioArgument) ;

void scanner_cocoa_routine_formerCompSupEgal (BOOL * ioScanningOk,
                UInt32 * ioArgument) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                    E X T E R N    F U N C T I O N S                       *
//                                                                           *
//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*
//                                                                           *
//         T E R M I N A L    S Y M B O L    E N U M E R A T I O N           *
//                                                                           *
//---------------------------------------------------------------------------*

enum {lexiqueBDD_1_,
  lexiqueBDD_1_nombre,
  lexiqueBDD_1_id,
  lexiqueBDD_1_string,
  lexiqueBDD_1_comp,
  lexiqueBDD_1__28_,
  lexiqueBDD_1__29_,
  lexiqueBDD_1__7B_,
  lexiqueBDD_1__7D_,
  lexiqueBDD_1__5B_,
  lexiqueBDD_1__5D_,
  lexiqueBDD_1__3A__3D_,
  lexiqueBDD_1__3A_,
  lexiqueBDD_1__2E_,
  lexiqueBDD_1__2E__2E_,
  lexiqueBDD_1__2B__3D_,
  lexiqueBDD_1__2D__3D_,
  lexiqueBDD_1__2D__3E_,
  lexiqueBDD_1__26_,
  lexiqueBDD_1__7C_,
  lexiqueBDD_1__7E_,
  lexiqueBDD_1__2C_,
  lexiqueBDD_1__3F_,
  lexiqueBDD_1__21_,
  lexiqueBDD_1__3B_,
  lexiqueBDD_1__23_,
  lexiqueBDD_1_ite_5F_cache,
  lexiqueBDD_1_and_5F_cache,
  lexiqueBDD_1_use_5F_and,
  lexiqueBDD_1_use_5F_ite,
  lexiqueBDD_1_use_5F_and_5F_ite,
  lexiqueBDD_1_map,
  lexiqueBDD_1_bdd,
  lexiqueBDD_1_domain,
  lexiqueBDD_1_bool,
  lexiqueBDD_1_record,
  lexiqueBDD_1_true,
  lexiqueBDD_1_false,
  lexiqueBDD_1_display,
  lexiqueBDD_1_include,
  lexiqueBDD_1_dump,
  lexiqueBDD_1_verify,
  lexiqueBDD_1_end,
  lexiqueBDD_1_if,
  lexiqueBDD_1_then,
  lexiqueBDD_1_else
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                     S C A N N E R    C L A S S                            *
//                                                                           *
//---------------------------------------------------------------------------*

@interface OC_Lexique_lexiqueBDD : OC_Lexique {
//--- Attributes
  @private NSMutableString * mLexicalAttribute_att_idf ;
  @private NSMutableString * mLexicalAttribute_att_token ;
  @private UInt32 mLexicalAttribute_att_valeur ;

}
//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


- (UInt32) terminalVocabularyCount ;

- (UInt32) styleIndexForTerminal: (SInt32) inTerminal ;

- (void) parseLexicalTokenForLexicalColoring ;

- (UInt32) styleCount ;

- (NSString *) styleNameForStyleIndex: (SInt32) inIndex ;

- (NSString *) styleIdentifierForStyleIndex: (SInt32) inIndex ;

- (BOOL) isTemplateLexique ;
@end

//---------------------------------------------------------------------------*
