//---------------------------------------------------------------------------*
//                                                                           *
//                           File 'syntaxeBDD.h'                             *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                       april 23th, 2006, at 21h7'5"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef syntaxeBDD_DEFINED
#define syntaxeBDD_DEFINED

#include <string.h>

#include "galgas/C_GGS_Object.h"
#include "galgas/AC_galgas_io.h"
#include "galgas/GGS_location.h"
#include "galgas/GGS_lbool.h"
#include "galgas/GGS_lchar.h"
#include "galgas/GGS_lstring.h"
#include "galgas/GGS_ldouble.h"
#include "galgas/GGS_luint.h"
#include "galgas/GGS_lsint.h"
#include "galgas/GGS_stringset.h"
#include "galgas/AC_galgas_map.h"
#include "lexiqueBDD.h"

// Include imported semantics
#include "semantiqueBDD.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Class Predeclarations                            *
//                                                                           *
//---------------------------------------------------------------------------*


void routine_exploreRecordDomain (C_Lexique &,
                                const GGS_typeDomainMap  &,
                                GGS_typeTableVariablesBool  &,
                                const GGS_location  & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                   Parser class syntaxeBDD declaration                     *
//                                                                           *
//---------------------------------------------------------------------------*

class syntaxeBDD {
  public : virtual ~syntaxeBDD (void) {}

  protected : virtual void nt_axiomeBDD_ (lexiqueBDD &,
                                GGS_typeTableFormules  &,
                                GGS_typeListeCalculs  &,
                                GGS_typeDomainMap  &) = 0 ;

  protected : virtual void nt_domainDefinition_ (lexiqueBDD &,
                                GGS_typeDomainMap  &,
                                GGS_typeDomain  &) = 0 ;

  protected : virtual void nt_formule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) = 0 ;

  protected : virtual void nt_type_formule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_lstring  ,
                                GGS_typeFormalArgumentsList  ,
                                GGS_luint  ,
                                GGS_typeCalcul  &) = 0 ;

  protected : virtual void nt_egalite_formule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) = 0 ;

  protected : virtual void nt_facteur_formule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) = 0 ;

  protected : virtual void nt_terme_formule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) = 0 ;

  protected : virtual void nt_dimension_ (lexiqueBDD &,
                                GGS_typeDomainMap  &,
                                GGS_typeDomain  &) = 0 ;

  protected : virtual void nt_comparaisonVariable_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_typeFormule  &) = 0 ;

  protected : virtual void nt_analyserFormule_ (lexiqueBDD &,
                                GGS_typeTableFormules  &,
                                GGS_typeDomainMap  &,
                                GGS_typeListeCalculs  &,
                                GGS_luint  ) = 0 ;

  protected : virtual void nt_argsFormelsFormule_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_typeDomainMap  &,
                                GGS_typeFormalArgumentsList  &) = 0 ;

  protected : virtual void nt_declarations_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_typeDomainMap  &,
                                GGS_typeFormalArgumentsList  &) = 0 ;

  protected : virtual void nt_parse_scalar_argument_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_location  &) = 0 ;

  protected : virtual void nt_parse_argument_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_typeVariableDescriptor  &,
                                GGS_location  &) = 0 ;

  protected : void pr_axiomeBDD_syntaxeBDD_112_17_ (lexiqueBDD &,
                                GGS_typeTableFormules  &,
                                GGS_typeListeCalculs  &,
                                GGS_typeDomainMap  &) ;

  protected : virtual sint16 select_repeat_syntaxeBDD_0 (lexiqueBDD &) = 0 ;

  protected : void pr_domainDefinition_syntaxeBDD_215_24_ (lexiqueBDD &,
                                GGS_typeDomainMap  &,
                                GGS_typeDomain  &) ;

  protected : virtual sint16 select_syntaxeBDD_1 (lexiqueBDD &) = 0 ;

  protected : virtual sint16 select_syntaxeBDD_2 (lexiqueBDD &) = 0 ;

  protected : virtual sint16 select_syntaxeBDD_3 (lexiqueBDD &) = 0 ;

  protected : virtual sint16 select_repeat_syntaxeBDD_4 (lexiqueBDD &) = 0 ;

  protected : void pr_analyserFormule_syntaxeBDD_269_23_ (lexiqueBDD &,
                                GGS_typeTableFormules  &,
                                GGS_typeDomainMap  &,
                                GGS_typeListeCalculs  &,
                                GGS_luint  ) ;

  protected : void pr_argsFormelsFormule_syntaxeBDD_290_26_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_typeDomainMap  &,
                                GGS_typeFormalArgumentsList  &) ;

  protected : virtual sint16 select_syntaxeBDD_5 (lexiqueBDD &) = 0 ;

  protected : void pr_declarations_syntaxeBDD_334_20_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_typeDomainMap  &,
                                GGS_typeFormalArgumentsList  &) ;

  protected : virtual sint16 select_repeat_syntaxeBDD_6 (lexiqueBDD &) = 0 ;

  protected : void pr_dimension_syntaxeBDD_374_17_ (lexiqueBDD &,
                                GGS_typeDomainMap  &,
                                GGS_typeDomain  &) ;

  protected : virtual sint16 select_syntaxeBDD_7 (lexiqueBDD &) = 0 ;

  protected : virtual sint16 select_syntaxeBDD_8 (lexiqueBDD &) = 0 ;

  protected : virtual sint16 select_syntaxeBDD_9 (lexiqueBDD &) = 0 ;

  protected : void pr_type_formule_syntaxeBDD_407_20_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_lstring  ,
                                GGS_typeFormalArgumentsList  ,
                                GGS_luint  ,
                                GGS_typeCalcul  &) ;

  protected : void pr_type_formule_syntaxeBDD_428_20_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_lstring  ,
                                GGS_typeFormalArgumentsList  ,
                                GGS_luint  ,
                                GGS_typeCalcul  &) ;

  protected : void pr_type_formule_syntaxeBDD_450_20_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_lstring  ,
                                GGS_typeFormalArgumentsList  ,
                                GGS_luint  ,
                                GGS_typeCalcul  &) ;

  protected : void pr_formule_syntaxeBDD_475_15_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : virtual sint16 select_repeat_syntaxeBDD_10 (lexiqueBDD &) = 0 ;

  protected : void pr_egalite_formule_syntaxeBDD_503_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : virtual sint16 select_repeat_syntaxeBDD_11 (lexiqueBDD &) = 0 ;

  protected : void pr_terme_formule_syntaxeBDD_524_21_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : virtual sint16 select_repeat_syntaxeBDD_12 (lexiqueBDD &) = 0 ;

  protected : void pr_facteur_formule_syntaxeBDD_545_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void pr_facteur_formule_syntaxeBDD_558_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void pr_facteur_formule_syntaxeBDD_570_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void pr_comparaisonVariable_syntaxeBDD_591_27_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_typeFormule  &) ;

  protected : void pr_comparaisonVariable_syntaxeBDD_608_27_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_typeFormule  &) ;

  protected : void pr_facteur_formule_syntaxeBDD_631_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void pr_facteur_formule_syntaxeBDD_643_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void pr_facteur_formule_syntaxeBDD_657_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void pr_facteur_formule_syntaxeBDD_678_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void pr_facteur_formule_syntaxeBDD_700_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void pr_facteur_formule_syntaxeBDD_719_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void pr_facteur_formule_syntaxeBDD_737_23_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : virtual sint16 select_repeat_syntaxeBDD_13 (lexiqueBDD &) = 0 ;

  protected : void pr_parse_argument_syntaxeBDD_778_22_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_typeVariableDescriptor  &,
                                GGS_location  &) ;

  protected : virtual sint16 select_repeat_syntaxeBDD_14 (lexiqueBDD &) = 0 ;

  protected : void pr_parse_scalar_argument_syntaxeBDD_803_29_ (lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_location  &) ;

} ;

//---------------------------------------------------------------------------*

#endif
