//---------------------------------------------------------------------------*
//                                                                           *
//                           File 'syntaxeBDD.h'                             *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                    february 10th, 2010, at 17h20'57"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef syntaxeBDD_DEFINED
#define syntaxeBDD_DEFINED

#include <string.h>

//---------------------------------------------------------------------------*

#include "galgas/GGS__header.h"
#include "lexiqueBDD.h"

//---------------------------------------------------------------------------*

// Include imported semantics
#include "semantiqueBDD.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Class Predeclarations                            *
//                                                                           *
//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*
//                                                                           *
//                      Routine 'exploreRecordDomain'                        *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_exploreRecordDomain (C_Compiler &,
                                const GGS_typeDomainMap  ,
                                GGS_typeTableVariablesBool  &,
                                GGS_uint  &,
                                const GGS_location   COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                   Parser class syntaxeBDD declaration                     *
//                                                                           *
//---------------------------------------------------------------------------*

class syntaxeBDD {
  public : virtual ~syntaxeBDD (void) {}

  protected : virtual void nt_axiomeBDD_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableFormules  &,
                                GGS_typeListeCalculs  &,
                                GGS_typeDomainMap  &) = 0 ;

  protected : virtual void nt_domainDefinition_ (C_Lexique_lexiqueBDD &,
                                GGS_typeDomainMap  &,
                                GGS_typeDomain  &) = 0 ;

  protected : virtual void nt_formule_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) = 0 ;

  protected : virtual void nt_type_5F_formule_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_lstring  ,
                                GGS_typeFormalArgumentsList  ,
                                GGS_luint  ,
                                GGS_typeCalcul  &) = 0 ;

  protected : virtual void nt_egalite_5F_formule_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) = 0 ;

  protected : virtual void nt_facteur_5F_formule_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) = 0 ;

  protected : virtual void nt_terme_5F_formule_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) = 0 ;

  protected : virtual void nt_dimension_ (C_Lexique_lexiqueBDD &,
                                GGS_typeDomainMap  &,
                                GGS_typeDomain  &) = 0 ;

  protected : virtual void nt_comparaisonVariable_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_typeFormule  &) = 0 ;

  protected : virtual void nt_analyserFormule_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableFormules  &,
                                GGS_typeDomainMap  &,
                                GGS_typeListeCalculs  &,
                                GGS_luint  ) = 0 ;

  protected : virtual void nt_argsFormelsFormule_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_uint  &,
                                GGS_typeDomainMap  &,
                                GGS_typeFormalArgumentsList  &) = 0 ;

  protected : virtual void nt_declarations_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_uint  &,
                                GGS_typeDomainMap  &,
                                GGS_typeFormalArgumentsList  &) = 0 ;

  protected : virtual void nt_parse_5F_scalar_5F_argument_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_location  &) = 0 ;

  protected : virtual void nt_parse_5F_argument_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_typeVariableDescriptor  &,
                                GGS_location  &) = 0 ;

  protected : void rule_syntaxeBDD_axiomeBDD_i0_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableFormules  &,
                                GGS_typeListeCalculs  &,
                                GGS_typeDomainMap  &) ;

  protected : virtual PMSInt16 select_syntaxeBDD_0 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : void rule_syntaxeBDD_domainDefinition_i1_ (C_Lexique_lexiqueBDD &,
                                GGS_typeDomainMap  &,
                                GGS_typeDomain  &) ;

  protected : virtual PMSInt16 select_syntaxeBDD_1 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : virtual PMSInt16 select_syntaxeBDD_2 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : virtual PMSInt16 select_syntaxeBDD_3 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : virtual PMSInt16 select_syntaxeBDD_4 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : void rule_syntaxeBDD_analyserFormule_i2_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableFormules  &,
                                GGS_typeDomainMap  &,
                                GGS_typeListeCalculs  &,
                                GGS_luint  ) ;

  protected : void rule_syntaxeBDD_argsFormelsFormule_i3_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_uint  &,
                                GGS_typeDomainMap  &,
                                GGS_typeFormalArgumentsList  &) ;

  protected : virtual PMSInt16 select_syntaxeBDD_5 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : void rule_syntaxeBDD_declarations_i4_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_uint  &,
                                GGS_typeDomainMap  &,
                                GGS_typeFormalArgumentsList  &) ;

  protected : virtual PMSInt16 select_syntaxeBDD_6 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : void rule_syntaxeBDD_dimension_i5_ (C_Lexique_lexiqueBDD &,
                                GGS_typeDomainMap  &,
                                GGS_typeDomain  &) ;

  protected : virtual PMSInt16 select_syntaxeBDD_7 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : virtual PMSInt16 select_syntaxeBDD_8 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : void rule_syntaxeBDD_type_5F_formule_i6_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_lstring  ,
                                GGS_typeFormalArgumentsList  ,
                                GGS_luint  ,
                                GGS_typeCalcul  &) ;

  protected : void rule_syntaxeBDD_type_5F_formule_i7_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_lstring  ,
                                GGS_typeFormalArgumentsList  ,
                                GGS_luint  ,
                                GGS_typeCalcul  &) ;

  protected : void rule_syntaxeBDD_type_5F_formule_i8_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_lstring  ,
                                GGS_typeFormalArgumentsList  ,
                                GGS_luint  ,
                                GGS_typeCalcul  &) ;

  protected : void rule_syntaxeBDD_formule_i9_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : virtual PMSInt16 select_syntaxeBDD_9 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : void rule_syntaxeBDD_egalite_5F_formule_i10_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : virtual PMSInt16 select_syntaxeBDD_10 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : void rule_syntaxeBDD_terme_5F_formule_i11_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : virtual PMSInt16 select_syntaxeBDD_11 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : void rule_syntaxeBDD_facteur_5F_formule_i12_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_facteur_5F_formule_i13_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_facteur_5F_formule_i14_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_comparaisonVariable_i15_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_comparaisonVariable_i16_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_luint  ,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_facteur_5F_formule_i17_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_facteur_5F_formule_i18_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_facteur_5F_formule_i19_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_facteur_5F_formule_i20_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_facteur_5F_formule_i21_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_facteur_5F_formule_i22_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : void rule_syntaxeBDD_facteur_5F_formule_i23_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  ,
                                GGS_uint  ,
                                GGS_typeDomainMap  &,
                                GGS_typeTableFormules  &,
                                GGS_typeFormule  &) ;

  protected : virtual PMSInt16 select_syntaxeBDD_12 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : void rule_syntaxeBDD_parse_5F_argument_i24_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_typeVariableDescriptor  &,
                                GGS_location  &) ;

  protected : virtual PMSInt16 select_syntaxeBDD_13 (C_Lexique_lexiqueBDD &) = 0 ;

  protected : void rule_syntaxeBDD_parse_5F_scalar_5F_argument_i25_ (C_Lexique_lexiqueBDD &,
                                GGS_typeTableVariablesBool  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_luint  &,
                                GGS_location  &) ;

} ;

//---------------------------------------------------------------------------*

#endif
